# -*- coding: utf-8 -*-
"""db_to_py.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1x8Xn3sF-AjaP4S-kAvCUpptWD9bjz762
"""

import psycopg2
import os
from psycog2.extras import RealDictCursor
from dotenv import load_dotenv

load_dotenv()

def fn_get_connection():
  return psycopg2.connect(
      host=os.getenv("DB_HOST"),
      port=os.getenv("DB_PORT"),
      database=os.getenv("DB_NAME"),
      user=os.getenv("DB_USER"),
      password=os.getenv("DB_PASSWORD"),
      cursor_factory=RealDictCursor
  )