# -*- coding: utf-8 -*-
"""main_to_py.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14Qx4ioT3NPXFb_f3iZVBhhzndpNE2Gzv
"""

from fastapi import FastAPI, Request
from db import fn_get_connection

app = FastAPI()

@app.get("/")
def read_root():
    return {"message": "Backend connected"}

@app.post("/query")
async def run_query(request: Request):
  data = await request.json()
  fn_name = data.get("function")
  params = data.get("params", {})

  try:
    conn = fn_get_connection()
    cur = conn.cursor()

    query = f"SELECT * FROM dwh.{fn_name}(%s, %s, %s, %s, %s);"

    cur.execute(query, (
        params["p_company_name"],
        params["p_venue_name"],
        params.get("p_week_number"),
        params.get("p_year"),
        params.get("p_month")
    ))

    result = cur.fetchall()

    cur.close()
    conn.close()

    return {"result": "success", "data": result}

  except Exception as e:
    return {"status": "error", "message": str(e)}